[package]
name = "fastiron-stats"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.3.5", features=["cargo", "derive"]}
csv = "1.2.2"
gnuplot = "0.0.38"