[package]
name = "fastiron-stats"
version = "1.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.8", features = ["cargo", "derive"] }
csv = "1.3.0"
gnuplot = "0.0.43"
