[package]
name = "fastiron"
version = "0.1.0"
edition = "2021"
about = "[This is an about text]"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4.1.4", features=["cargo", "derive"]}
serde = {version="1.0.152", features=["derive"]}
serde_yaml = {version="0.9.17", features=[]}